name: build-image
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      LOGIN_SERVER: uselessregistry.azurecr.io
      REPO_NAME: react-base
      USER_NAME: uselessRegistry
    steps:
      - uses: actions/checkout@main
        env:
          PWD: ${{ secrets.AZURE_PUSH_KEY }}
        run: echo $PWD | docker login $LOGIN_SERVER --username $USER_NAME --password-stdin
      - run: docker build -t $LOGIN_SERVER/$REPO_NAME:latest .
      - run: docker push $LOGIN_SERVER/$REPO_NAME:latest